### ISSUE TITLE
Change *.DURAL files to *.LEPTO

### ISSUE THREAD

**Issue by dmgroppe** [epiSurg/EpiSurg#44]
“Leptomeningeal Surface” is more accurate than "Dural Surface" to describe smoothed Pial Surface

**Comment by epiSurg** [comment]
iELVis has been updated so that the smoothed pial surface is called the "leptomeningeal surface" instead of "dural surface." To make previous data compatible with the new code, just change the *.DURAL and *.DURALVOX file in the patient's elec_recon folder to *.LEPTO and *.LEPTOVOX. Our apologies for any inconvenience.
